spring:
  data:
    redis:
      host: localhost
      port: 6381
      password: mypass
      timeout: 3000

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.http.converter.json: DEBUG