### Redis API Test
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "id":1,
  "username": "testUser",
  "email": "test@example.com2"
}

### 점수 등록
POST http://localhost:8080/api/leaderboard/scores?userId=user1&score=100
Content-Type: application/json

### 상위 플레이어 조회
GET http://localhost:8080/api/leaderboard/top/10

### 특정 사용자 조회
GET http://localhost:8080/api/users/1

### 랭킹
GET http://localhost:8080/api/leaderboard/rank/user1